### ISSUE TITLE
csv 파싱 데이터 DB에 넣기...

### ISSUE THREAD

**Issue by thing-zoo** [team-11-challenge/back-end#2]
college 엔티티를 넣는데 자꾸만 중복으로 데이터가 들어가서

org.springframework.dao.DataIntegrityViolationException

위와 같은 에러가 발생...!

**Comment by klettermi** [comment]
파싱 문제 발생

- 강의 시간에 큰 따옴표로 구분자를 고려하였다. 그러나 다른 데이터에도 큰 따옴표가 들어간 것을 확인했다. 큰 따옴표로 구분자를 사용함으로써 파싱에 문제가 있음이 확인되었다.
- 이 문제를 해결하기 위해서 csv를 자동적으로 구분해주는 CSVReader를 도입하였다.

- 강의 시간이 없는 경우 전처리 시 공백이 되게 되는데 이를 처리해주는 로직이 없었다.(산학협력단, 교원양성지원센터 데이터)
- 이 문제를 해결하기 위해 공백을 전처리해주는 경우를 추가해주었다.

Unique key 중복 처리 문제

- 계속적으로 Unique key가 중복되어 에러가 발생하였다.
- 중복을 미리 처리하는 함수를 만들어 중복 처리에 대한 문제를 해결해주었다.
- 또한 parallel stream이 기본적으로 병렬로 실행되어 각 스레드가 다른 스레드와 중복된 데이터를 처리하여 unique 제약 조건을 위반하게 되어 무결성 위반 문제가 발생하였다. 이처럼 동시적 문제를 해결하기 위해서 parallel를 제거하였다.
